### ISSUE TITLE
Link to this project from ns-api

### ISSUE THREAD

**Issue by aquatix** [bartromgens/nsmaps#6]
Hey, is it ok if I link to your nsmaps repo from the ns-api README noting it as a project that uses it?

**Comment by bartromgens** [comment]
Sure! I would like that.

**Comment by aquatix** [comment]
Added at https://github.com/aquatix/ns-api#also-take-a-look-at-nsmaps Will be officially released whenever there's a new ns-api version :)

**Comment by bartromgens** [comment]
Nice!
